---
services:
  mytunes-portal:
    container_name: mytunes-portal
    image: bernhardfritz/mytunes-portal:latest
    build: .
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.mytunes-portal-https.tls=true
      - traefik.http.routers.mytunes-portal-https.tls.certresolver=cloudflare
      - traefik.http.routers.mytunes-portal-https.entrypoints=websecure
      - traefik.http.routers.mytunes-portal-https.rule=(Host(`mytunes.example.com`)&&Path(`/`))||(Host(`mytunes.example.com`)&&Path(`/_vlc`))
      - traefik.http.routers.mytunes-portal-https.middlewares=traefik-forward-auth
    restart: unless-stopped
    environment:
      - MYTUNES_PORTAL_KEY=${MYTUNES_PORTAL_KEY}
networks:
  proxy:
    external: true