---
include:
  - traefik/docker-compose.yaml
  - mytunes-portal/docker-compose.yaml
  - cloudflared/docker-compose.yaml
  - crowdsec/docker-compose.yaml
services:
  mytunes:
    container_name: mytunes
    image: bernhardfritz/mytunes:latest
    build: .
    volumes:
      - ./data:/var/lib/mytunes:ro
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.mytunes-https.tls=true
      - traefik.http.routers.mytunes-https.tls.certresolver=cloudflare
      - traefik.http.routers.mytunes-https.entrypoints=websecure
      - traefik.http.routers.mytunes-https.rule=Host(`mytunes.example.com`)
      - "traefik.http.routers.mytunes-https.middlewares=crowdsec@docker, traefik-forward-auth"
      - traefik.http.middlewares.crowdsec.plugin.bouncer.enabled=true
      - traefik.http.middlewares.crowdsec.plugin.bouncer.crowdseclapikey=${BOUNCER_KEY_TRAEFIK}
      - traefik.http.middlewares.crowdsec.plugin.bouncer.loglevel=DEBUG
      - traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecappsecenabled=true
      - traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecappsechost=crowdsec:7422
    restart: unless-stopped
networks:
  proxy:
    external: true