# Open in browser, click authorize and copy code from query params:
# https://discord.com/oauth2/authorize?response_type=code&client_id=changeme&redirect_uri=https%3A%2F%2Fmytunes.changeme.duckdns.org%2F_oauth&scope=identify%20email

# @name token
POST https://discord.com/api/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code
&code=changeme
&redirect_uri=https://mytunes.changeme.duckdns.org/_oauth
&client_id={{$dotenv PROVIDERS_DISCORD_CLIENT_ID}}
&client_secret={{$dotenv PROVIDERS_DISCORD_CLIENT_SECRET}}
###

@token_type = {{token.response.body.token_type}}
@access_token = {{token.response.body.access_token}}

GET https://discord.com/api/users/@me
Authorization: {{token_type}} {{access_token}}