---
services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.3.4
    container_name: reverse-proxy
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./data/certs/:/var/traefik/certs/:rw
    restart: unless-stopped
    networks:
      - proxy
  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:v2.2.0
    container_name: traefik-forward-auth
    environment:
      - DEFAULT_PROVIDER=generic-oauth
      - PROVIDERS_GENERIC_OAUTH_AUTH_URL=https://discord.com/oauth2/authorize
      - PROVIDERS_GENERIC_OAUTH_TOKEN_URL=https://discord.com/api/oauth2/token
      - PROVIDERS_GENERIC_OAUTH_USER_URL=https://discord.com/api/users/@me
      - PROVIDERS_GENERIC_OAUTH_CLIENT_ID=${PROVIDERS_DISCORD_CLIENT_ID}
      - PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET=${PROVIDERS_DISCORD_CLIENT_SECRET}
      - PROVIDERS_GENERIC_OAUTH_SCOPE=identify,email
      - SECRET=${SECRET}
      - LOG_LEVEL=debug
      - WHITELIST=${WHITELIST}
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
    networks:
      - proxy
networks:
  proxy:
    external: true