global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
# api:
#   dashboard: true
#   insecure: true
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    forwardedHeaders:
      trustedIPs:
        - "172.18.0.42"
certificatesResolvers:
  cloudflare:
    acme:
      email: "changeme@gmail.com"
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: 'https://acme-v02.api.letsencrypt.org/directory'
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
accessLog:
  filePath: /var/log/traefik/access.log
experimental:
  plugins:
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.4.4