name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: go mod download && go mod verify
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test ./...
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push mytunes
        run: |
          docker build --platform=linux/arm/v6 -t bernhardfritz/mytunes-armv6:latest .
          docker push bernhardfritz/mytunes-armv6:latest
      
      - name: Build and push mytunes-portal
        run: |
          docker build --platform=linux/arm/v6 -t bernhardfritz/mytunes-portal-armv6:latest ./mytunes-portal
          docker push bernhardfritz/mytunes-portal-armv6:latest